### ISSUE TITLE
Some MAC-OS-systems don't support serial-connection

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#119] opened 2021-05-21 10:32 UTC
High Sierra gives a 'robot not found'.
There seems to be a problem with the USB-driver.
The Arduino Ide seems to have the same problem.

A possible solution:
https://drive.google.com/file/d/1lUYkw-mCOekJjY1MVA5YuEbERHNWNCZW/view

With this video as tutorial:
https://www.youtube.com/watch?v=nJOvzivDuag

**Comment by paulsiersma** [comment] 2021-08-31 17:41
@Roelandsmith I seem to remember us discussing this and deciding that this problem is better fixed by adding documentation ie explaining to people how to apply the fixes described in your links. The problem is not specific to Leaphy and will be very hard, if not impossible to fix in an automated way. So I am closing this, feel free to reopen if you disagree.

**Closed by paulsiersma** 2021-08-31 17:41 UTC
Labels: bug
